### ISSUE TITLE
hazard data translate

### ISSUE THREAD

**Issue by softloud** [softloud/sysrevdata#10]
possibly duplicated articles

when it's converted, either extra rows or losing rows

**Comment by DrMattG** [comment]
The problem is in line 217 in the code. 
`dplyr::rename_with(snakecase::to_snake_case) 
Error: Names must be unique.
x These names are duplicated:
  * "hazard_increased_frequency_and_intensity_of_extreme_heat_drought_other_1" at locations 223 and 494.`
