### ISSUE TITLE
long to condensed optimise

### ISSUE THREAD

**Issue by softloud** [softloud/sysrevdata#20]
doesn't run fast enough; @softloud will try with `::map` functions to see if it improves

note from @nealhaddaway 

- The vegetated strips map database is a good wide example to play with

**Comment by softloud** [comment]
Hi @nealhaddaway, I'm taking a look at `long_to_wide`, I have some ideas about how to improve the time, but I'm struggling to get the code to run. Could you throw me a reprex so I can see the output? 

To create a reprex
```
install.packages("reprex")
```
then copy the code to the clipboard and run
```
reprex::reprex()
```
from the console and it will copy to your clipboard a reprex you can paste here.

**Comment by nealhaddaway** [comment]
Will do - probably not before the end of this week tho. On leave now.

Sent from my iPhone

On 15 Nov 2020, at 06:03, Charles T. Gray <notifications@github.com> wrote:

﻿

Hi @nealhaddaway<https://github.com/nealhaddaway>, I'm taking a look at long_to_wide, I have some ideas about how to improve the time, but I'm struggling to get the code to run. Could you throw me a reprex so I can see the output?

To create a reprex

install.packages("reprex")


then copy the code to the clipboard and run

reprex::reprex()


from the console and it will copy to your clipboard a reprex you can paste here.

**Comment by softloud** [comment]
Oh no rush at all, whenever you get around to it :) Enjoy leave :tada:
:croissant:
