### ISSUE TITLE
ESMAR talk

### ISSUE THREAD

**Issue by softloud** [softloud/sysrevdata#26]
Hey @DrMattG I put the [talk on my blog](https://github.com/softloud/onetimetrophybitch/tree/master/talks/sysrevdat) as I haven't figured out how to embed a talk in pkgdown yet - but if I do I'll move it over.
 
Just threw up an outline to get us started. Thoughts on the outline? And, of course, content.

**Comment by softloud** [comment]
- [ ] Try embedding using this suggestion from @ha0ye :pray: 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Yes, though there is a bit of extra hand-holding to get the xarigan slides rendered properly (because pkgdown likes to use its own html format for any Rmd files).<br><br>Example: <a href="https://t.co/grpbl02YzR">https://t.co/grpbl02YzR</a><br>Template (with GitHub actions script): <a href="https://t.co/XSeGS0vLQT">https://t.co/XSeGS0vLQT</a></p>&mdash; Hao Ye (@Hao_and_Y) <a href="https://twitter.com/Hao_and_Y/status/1351349271463948290?ref_src=twsrc%5Etfw">January 19, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by DrMattG** [comment]
Structure looks great!

**Comment by softloud** [comment]
[Slides](https://github.com/softloud/sysrevdata) are up @DrMattG. I feel like a fraud; I can speak about data engineering, but don't feel confident about systematic review data. Thoughts, comments, improvements?

**Comment by DrMattG** [comment]
> [Slides](https://softloud.github.io/onetimetrophybitch/talks/sysrevdat/sysrevdat-talk.html#1) are up @DrMattG. I feel like a fraud; I can speak about data engineering, but don't feel confident about systematic review data. Thoughts, comments, improvements?
> 
> Will you be presenting with me? I feel like the least experienced of the authors. Would feel better about it if we were bouncing off each other.

I can be there with you - Dont feel like a fraud - you are talking about what you know -- the data engineering is important. 

I think we need to mention in the start that there is a lack of standardisatiion of databases and thus that is a big barrier to open synthesis

**Comment by DrMattG** [comment]
Sorry I cant spell!

**Comment by softloud** [comment]
Excellent point about standardisation, updated the slides with that as a point in first slide :+1:

**Comment by softloud** [comment]
I'm going to record the nma talk in the break after the next session. There's a 3 hour break, right? Perhaps we could meet then, too, too, smash out the recording, iron out the kinks of the presentation?

**Comment by DrMattG** [comment]
I've got to head out for a bit in the break but will let you know when I get back
