### ISSUE TITLE
Font size in tooltips is small

### ISSUE THREAD

**Issue by DrMattG** [softloud/sysrevdata#34]
Solution here: https://github.com/JohnCoene/tippy/issues/7

**Comment by DrMattG** [comment]
That doesn't seem to work in pkgdown or markdown.....

**Comment by nealhaddaway** [comment]
We can use CSS directly, I think - something like tippy("main text", <span style='font-size:20px;'>"tooltip text"</span>) should work.
________________________________

**Comment by DrMattG** [comment]
Solved using @nealhaddaway 's code. Closing this issue now.
