### ISSUE TITLE
Have a check pre-submission

### ISSUE THREAD

**Issue by DrMattG** [softloud/sysrevdata#38]
- [x] @softloud check that I haven't made a mess of the narrative vignette
- [x] @nealhaddaway what do you think of the machine readable vignette - perhaps we need more tool tips? Not sure if the text is quite right in places but should be okay for resubmission....

**Comment by softloud** [comment]
- [ ] fix titles of vignettes

**Comment by softloud** [comment]
- [ ] titles of vignettes are not in the same format. Narrative synthesis table vignette needs name update. For some reason I thought it needed to be a single word

**Comment by softloud** [comment]
I thought this would be a useful example to stick into the complex summaries/visualisations. 

Number of observations per category per study:

```
buffer_example_long %>% 
  count(short_title, category_type) %>% 
  pivot_wider(
    id_cols = short_title,
    names_from = category_type,
    values_from = n
  )
```
